version: '2'
services:
  cygnus-ngsi:
    restart: always
    build: .
    ports:
     - "5050:5050"
     - "8081:8081"
    tty: true
    volumes:
     - ./agent_mongo.conf:/usr/cygnus/conf/agent_mongo.conf:ro
     - ./cygnus_instance_mongo.conf:/usr/cygnus/conf/cygnus_instance_mongo.conf:ro
  mongo:
    image: 'bitnami/mongodb'
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./db/mongo/:/bitnami/mongodb/"
  #postgreSQL:
     #restart: always
     #image: sameersbn/postgresql
     #ports:
      #- "5432:5432"
     #environment:
      #- DEBUG=true
      #- DB_USER=root
      #- DB_PASS=password
      #- DB_NAME=postgres
     #volumes:
      #- "./db/postgresql/:/var/lib/postgresql/"
